### ISSUE TITLE
Extension Test Runner breaks GitHub Pull Requests

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-extension-test-runner#42]
1. Install both Extension Test Runner and GitHub Pull Requests
2. Clone https://github.com/microsoft/vscode and open in VS Code.  (I've only seen the issue with this repo)
3. Open the Pull Requests view, wait for the PRs to load, then refresh the view
4. 🐛Lots of errors saying `Protocol "https:" not supported. Expected "http:"`
5. Uninstall Extension Test Runner and repeat step 3 to say that the errors only occur with Extension Test Runner.

Reported in https://github.com/microsoft/vscode-pull-request-github/issues/6088, found thanks to extension bisect.

**Comment by connor4312** [comment]
It's a weird issue.

1. The extension test runner evaluates code in `test.ts` files. In the colorizer tests it ends up in a case where it passes one of our "placeholder" objects to `path.join()`. In some internals this ends up somehow 'poisoning' the Error object such that stack traces stop working.
1. We don't set a `protocol` on the proxy `BaseAgent`
2. Therefore the agent falls back to capturing an error stack trace and looking in there to try to figure out its protocol https://github.com/TooTallNate/proxy-agents/blob/main/packages/agent-base/src/index.ts#L67-L78
  3. We should set the agent protocol to avoid any such extension interference in the future @chrmarti 
4. The stack trace is empty and so the agent guesses plain http instead of https

I will sanitize out any placeholders when passed to imported functions.
